version: '3.9'

services:
  be-sample:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: be-sample-${ENV}
    command: >
      sh -c "
        npm run migrate &&
        npm run seed &&
        npm run start:prod
      "
    env_file:
      - .env
    ports:
      - '${DOCKER_PORT}:3000'
    volumes:
      - ./public:/app/public
    networks:
      - be-sample-network
    restart: always

networks:
  be-sample-network:
    driver: bridge
