version: '3.9'

services:
  be-sample:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: be-sample-${ENV}
    command: >
      sh -c "
        rm -rf node_modules package-lock.json &&
        echo 'ğŸ“¦ Installing Library...' && npm install &&
        echo 'ğŸ—ï¸ Building app...' && npm run build &&
        echo 'ğŸ“¦ Migrate Database...' && npm run migrate &&
        echo 'ğŸ“¦ Seeding Database...' && npm run seed &&
        echo 'ğŸš€ Starting app...' && npm run start:prod
      "
    env_file:
      - .env
    ports:
      - '${DOCKER_PORT}:3000'
    volumes:
      - .:/app
    networks:
      - be-sample-network

networks:
  be-sample-network:
    driver: bridge